name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: |
            yamato-chrome.zip
            yamato-firefox.xpi
